<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByVideo($video, int $first_result = 0, int $max_results = 25){
        return $this->findByVideo($video, ['datetime' => 'desc'], $max_results, $first_result);
    }
}
