<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function search(string $search): array {
        $qb = $this->createQueryBuilder('u');
        $query = $qb
            ->where($qb->expr()->like('u.username', "'%".$search."%'"))
            ->getQuery();
        
        return $query->getResult();
    }
}
