<?php

namespace AppBundle\Repository;

/**
 * VideoCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoCategoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllExceptDefault(){
        $qb = $this->createQueryBuilder('vc');
        $query = $qb
            ->where("vc.name NOT LIKE 'Default'")
            ->getQuery();

        return $query->getResult();
    }
}
