home:
    path:       /
    defaults:   { _controller: AppBundle:Default:home }

search:
    path:       /search
    defaults:   { _controller: AppBundle:Default:search }

video_show:
    path:       /video/{id}
    defaults:   { _controller: AppBundle:Video:show }
    requirements:
        id:     '\d+'

video_new:
    path:       /video/new
    defaults:   { _controller: AppBundle:Video:new }

video_edit:
    path:       /video/{id}/edit
    defaults:   { _controller: AppBundle:Video:edit }
    requirements:
        id:     '\d+'

video_delete:
    path:       /video/{id}/delete
    defaults:   { _controller: AppBundle:Video:delete }
    requirements:
        id:     '\d+'

video_list_category:
    path:       /category/{name}/videos
    defaults:   { _controller: AppBundle:Video:listByCategory}

video_list_user:
    path:       /user/{id}/videos
    defaults:   { _controller: AppBundle:Video:listByUser}
    requirements:
        id:     '\d+'

comment_new:
    path:       /comment/new
    defaults:   { _controller: AppBundle:Comment:new }
    options:
        expose: true

comment_get:
    path:       /comment/{video_id}/{first_result}
    defaults:   { _controller: AppBundle:Comment:new, first_result: 0 }
    requirements:
        video_id: '\d+'
        first_result: '\d+'

video_category_list:
    path:       /category/{name}
    defaults:   { _controller: AppBundle:VideoCategory:listVideos}

history:
    path:       /history
    defaults:   { _controller: AppBundle:User:history }