home:
    path:       /
    defaults:   { _controller: AppBundle:Video:index }

video_show:
    path:       /video/{id}
    defaults:   { _controller: AppBundle:Video:show }
    requirements:
        id:     '\d+'

video_new:
    path:       /video/new
    defaults:   { _controller: AppBundle:Video:new }

comment_new:
    path:       /comment/new
    defaults:   { _controller: AppBundle:Comment:new }
    options:
        expose: true

comment_get:
    path:       /comment/{video_id}/{first_result}
    defaults:   { _controller: AppBundle:Comment:new, first_result: 0 }
    requirements:
        video_id: '\d+'
        first_result: '\d+'