home:
    path:       /
    defaults:   { _controller: AppBundle:Video:index }

video_show:
    path:       /video/{id}
    defaults:   { _controller: AppBundle:Video:show }
    requirements:
        id:     '\d+'

video_new:
    path:       /video/new
    defaults:   { _controller: AppBundle:Video:new }

comment_new:
    path:       /comment/{video_id}/new
    defaults:   { _controller: AppBundle:Comment:new }
    requirements:
        video_id: '\d+'