home:
    path:       /
    defaults:   { _controller: AppBundle:Video:index }

video_show:
    path:       /video/{id}
    defaults:   { _controller: AppBundle:Video:show }
    requirements:
        id:     '\d+'

video_add:
    path:       /video/add
    defaults:   { _controller: AppBundle:Video:add }
